# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maike Negreiros
email: maike_jbe@hotmail.com
description: Falo sobre tecnologia e programação, principalmente JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maikenegreiros.me" # the base hostname & protocol for your site
twitter_username: maikenegreiros
github_username:  maikenegreiros
permalink: /:categories/:title
# Build settings
markdown: kramdown

